url: http://portfolio.gearchicken.com
baseurl: /

# Site settings
title: Liam Middlebrook
email: liammiddlebrook@gmail.com
description: "Liam Middlebrook's Portfolio Website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/liam-middlebrook
  - title: twitter
    url: http://twitter.com/liammiddlebrook
  - title: stack-overflow
    url: http://stackoverflow.com/users/1233554/loothelion
  - title: bitbucket 
    url: http://bitbucket.org/liam-middlebrook

# Build settings
markdown: kramdown
permalink: pretty
