url: http://gearchicken.com
baseurl: /portfolio

# Site settings
title: Liam Middlebrook
email: liammiddlebrook@gmail.com
description: "Liam Middlebrook's Portfolio Website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
#people:
#- name: Liam Middlebrook
#  pic: 1
#  position: Engine Developer
#  social:
#    - title: twitter
#      url: http://twitter.com/liammiddlebrook
#    - title: github
#      url: https://github.com/liam-middlebrook

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/liammiddlebrook
  - title: stack-overflow
    url: http://stackoverflow.com/users/1233554/loothelion
  - title: bitbucket 
    url: http://bitbucket.org/liam-middlebrook
  - title: github
    url: http://github.com/liam-middlebrook

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
